using JuAFEMGmsh

JuAFEMGmsh.gmsh.initialize()
JuAFEMGmsh.gmsh.option.setNumber("General.Terminal", 1)
JuAFEMGmsh.gmsh.model.add("t1")
lc = 1e-2
JuAFEMGmsh.gmsh.model.geo.addPoint(0, 0, 0, lc, 1)
JuAFEMGmsh.gmsh.model.geo.addPoint(.1, 0,  0, lc, 2)
JuAFEMGmsh.gmsh.model.geo.addPoint(.1, .3, 0, lc, 3)
JuAFEMGmsh.gmsh.model.geo.addPoint(0, .3, 0, lc, 4)
JuAFEMGmsh.gmsh.model.geo.addLine(1, 2, 1)
JuAFEMGmsh.gmsh.model.geo.addLine(3, 2, 2)
JuAFEMGmsh.gmsh.model.geo.addLine(3, 4, 3)
JuAFEMGmsh.gmsh.model.geo.addLine(4, 1, 4)
JuAFEMGmsh.gmsh.model.geo.addCurveLoop([4, 1, -2, 3], 1)
JuAFEMGmsh.gmsh.model.geo.addPlaneSurface([1], 1)
JuAFEMGmsh.gmsh.model.addPhysicalGroup(0, [1, 2], 1)
JuAFEMGmsh.gmsh.model.addPhysicalGroup(1, [1, 2], 2)
JuAFEMGmsh.gmsh.model.addPhysicalGroup(2, [1], 6)
JuAFEMGmsh.gmsh.model.setPhysicalName(2, 6, "My surface")
JuAFEMGmsh.gmsh.model.geo.synchronize()
JuAFEMGmsh.gmsh.model.mesh.generate(2)
