name = "FerriteGmsh"
uuid = "4f95f4f8-b27c-4ae5-9a39-ea55e634e36b"
authors = ["Maximilian Köhler <maximilian.koehler@ruhr-uni-bochum.de>"]
version = "0.1.0"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
gmsh_jll = "630162c2-fc9b-58b3-9910-8442a8a132e6"

[compat]
Ferrite = "0.3"
