name = "FerriteGmsh"
uuid = "4f95f4f8-b27c-4ae5-9a39-ea55e634e36b"
authors = ["Maximilian Köhler <maximilian.koehler@ruhr-uni-bochum.de>"]
version = "1.0.1"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"

[compat]
Ferrite = "0.3,0.4"
Gmsh = "0.2.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
