name = "FerriteGmsh"
uuid = "4f95f4f8-b27c-4ae5-9a39-ea55e634e36b"
authors = ["Maximilian Köhler <maximilian.koehler@ruhr-uni-bochum.de>"]
version = "0.1.0"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
gmsh = "a3f5b5a8-4c56-11eb-214e-350f4127dda5"
